version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
    - graphviz

sphinx:
  configuration: doc/conf.py
  builder: html
  fail_on_warning: true

python:
  install:
    - requirements: doc/requirements.txt
