#!/bin/sh
a="$1"
b="${a}"

b="${b%* *}"
b="${b%*	*}"
b="${b%*
*}"
b="${b%*\\*}"
b="${b%*:*}"
b="${b%*;*}"

if [ "$a" != "$b" ]; then
    echo "contains invalid characters" >&2
    exit 1
fi

echo " ${a}"
